# Generated by Django 2.2.2 on 2019-06-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=50)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.Todo')),
            ],
        ),
    ]
